# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - run: npm run build
      - run: npm test

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Print Working Directory
        run: pwd

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          CI: false
        if: success() # Выполнять только при успешной сборке
